### ISSUE TITLE
Question - how to install?

### ISSUE THREAD

**Issue by gudata** [asandeep/airflow-ecr-plugin#6]
Hello,
I am running airflow from a docker containers.
I have installed on the base image the plugin. That means that it should be available on all the containers (worker, scheduler, webserver, ..)
```
pip install airflow-ecr-plugin
```
I have also added the dag in the dags/ folder

I tried to put setup.py in the plugins/ then I tried to put it in the dags/ folder.
I constantly get that error:
```
Broken DAG: [/opt/airflow/dags/refreshECRtokens.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/refreshECRtokens.py", line 4, in <module>
    from airflow.operators import aws_ecr
ImportError: cannot import name 'aws_ecr'
```

Please help by pointing how to install it that plugin.

**Comment by asandeep** [comment]
Hey @gudata,

You can follow the instructions in [Getting Started section](https://github.com/asandeep/airflow-ecr-plugin#getting-started) to load the plugin in your package. For `setup.py` add below:

```python
from setuptools import setup

setup(
    name="my-package",
    ...
    entry_points = {
        'airflow.plugins': [
            'aws_ecr = airflow_ecr_plugin:AwsEcrPlugin'
        ]
    }
)
```

Hope this helps.

**Comment by gudata** [comment]
I don't have a package because my dags will use the airflow docker operator to run the python code and I am not familiar with using packages with airflow.

I do not get where to put setup.py file. I tried to put it and the plugins folder but the dag failed.

**Comment by asandeep** [comment]
Ah. In that case, can you try using the operator directly?
It should import like any other python package.

```python
import airflow
from airflow_ecr_plugin import operators


REFRESH_ECR_TOKEN_DAG = airflow.DAG(...)

operators.RefreshEcrDockerConnectionOperator(
    task_id=<task_id>,
    ecr_docker_conn_id=<docker_conn_id>,
    ecr_region=<ecr_region>,
    aws_conn_id=<aws_conn_id>,
    dag=REFRESH_ECR_TOKEN_DAG,
)
```

**Comment by gudata** [comment]
Still not working. I created a aws_default connection, with empty fields because I use the EC2 role on the machine.
I created the dag
```
from datetime import datetime, timedelta
from airflow import DAG
from airflow_ecr_plugin import operators

with DAG('OPERATORzz2',
         start_date=datetime(2021, 1, 1),
         max_active_runs=1,
         schedule_interval='@daily',
         ) as dag:

    operators.RefreshEcrDockerConnectionOperator(
        task_id='will',
        ecr_docker_conn_id="docker_default_2",
        ecr_region="eu-central-1",
        aws_conn_id="aws_default",
        dag=dag,
    )

```

And I have that error

```
[2021-10-22, 10:51:42 UTC] {logging_mixin.py:109} INFO - Running <TaskInstance: OPERATORzz2.will scheduled__2021-01-07T00:00:00+00:00 [running]> on host 172.18.0.7
[2021-10-22, 10:51:45 UTC] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=OPERATORzz2
AIRFLOW_CTX_TASK_ID=will
AIRFLOW_CTX_EXECUTION_DATE=2021-01-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-07T00:00:00+00:00
[2021-10-22, 10:51:45 UTC] {warnings.py:99} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow_ecr_plugin/hooks.py:39: DeprecationWarning: This class is deprecated. Please use `airflow.providers.amazon.aws.hooks.base_aws.AwsBaseHook`.
  super(AwsEcrHook, self).__init__(aws_conn_id, verify)

[2021-10-22, 10:51:45 UTC] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow_ecr_plugin/operators.py", line 41, in execute
    aws_conn_id=self.aws_conn_id, region_name=self.ecr_region
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow_ecr_plugin/hooks.py", line 39, in __init__
    super(AwsEcrHook, self).__init__(aws_conn_id, verify)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 393, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-10-22, 10:51:46 UTC] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=OPERATORzz2, task_id=will, execution_date=20210107T000000, start_date=20211022T105138, end_date=20211022T105146
[2021-10-22, 10:51:47 UTC] {standard_task_runner.py:91} ERROR - Failed to execute job 462 for task will
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow_ecr_plugin/operators.py", line 41, in execute
    aws_conn_id=self.aws_conn_id, region_name=self.ecr_region
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow_ecr_plugin/hooks.py", line 39, in __init__
    super(AwsEcrHook, self).__init__(aws_conn_id, verify)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 393, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-10-22, 10:51:47 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-10-22, 10:51:48 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by asandeep** [comment]
@gudata I was able to reproduce the error on Airflow v2.2.0

Unfortunately at the time of development Airflow v2 wasn't out and I see that there has been significant changes in provider packages in v2. So, sadly the plugin will only work with Airflow v1 for now.

As a workaround, I can suggest you taking a look at [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) package that automatically takes care of refreshing the ECR token to fetch the image.

You can install it on the machine/s where images from ECR will be pulled and executed. Hope this helps!
